### ISSUE TITLE
ImportError: No module named read_until.read_until

### ISSUE THREAD

**Issue by fanavarro** [harrisonedwards/RUBRIC#1]
Hello Harrison, I'm writing to you because I'm trying to use RUBRIC, but I can't.
I have followed the installation steps in the README.md file without any problem. However, when I run the application with:
`python RUBRIC -h`
I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/minion/RUBRIC/RUBRIC/__main__.py", line 18, in <module>
    from read_until.read_until import ReadUntil
ImportError: No module named read_until.read_until
```
I though that this dependency was already included in the application. I have not found this library anywhere. How can I fix this issue?

Regards and thanks in advance,
Fran.

**Comment by harrisonedwards** [comment]
Hi Fran,
Unfortunately I have had to temporarily remove the read until API that was originally included.  I am working to get permission from ONT to include it with RUBRIC (as it is an older version that I suspect they aren't as protective of) but they are currently checking that everything is kosher on their end.  
It is possible that you can email them directly and note that you need version 1 of the API in the meantime.  
I hope to soon be able to include it in the repo.
Thanks,
Harrison
